export const driverNames: string[] = [
    'pierre gasly',
    'franco colapinto',
    'fernando alonso',
    'lance stroll',
    'lewis hamilton',
    'charles leclerc',
    'esteban ocon',
    'oliver bearman',
    'nico hülkenberg',
    'gabriel bortoleto',
    'lando norris',
    'oscar piastri',
    'george russell',
    'kimi antonelli',
    'liam lawson',
    'isack hadjar',
    'max verstappen',
    'yuki tsunoda',
    'carlos sainz',
    'alexander albon'
];
